sonar.projectKey=Hexfields-Studio_HexfieldsDominion
sonar.organization=hexfields-studio
sonar.projectName=HexfieldsDominion
sonar.sources=src
sonar.tests=src
sonar.exclusions=**/*.test.tsx,**/*.spec.tsx,src/test/**

# Coverage configuration
sonar.javascript.lcov.reportPaths=./coverage/lcov.info

# Typescript configuration
sonar.typescript.exclusions=**/*.test.tsx,**/*.spec.tsx
sonar.typescript.lcov.reportPaths=./coverage/lcov.info

# Test inclusion
sonar.test.inclusions=**/*.test.tsx,**/*.spec.tsx
